# Generated by Django 4.2 on 2025-10-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Inscrit'), ('DROPPED', 'Abandonné'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué')], default='ENROLLED', max_length=20, verbose_name='Statut')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('drop_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'abandon")),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursesection', verbose_name='Section de cours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course_section')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20, verbose_name='Statut précédent')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enrollments.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': "Historique d'inscription",
                'verbose_name_plural': "Historiques d'inscription",
                'ordering': ['-changed_at'],
            },
        ),
    ]
