# Generated by Django 4.2.16 on 2026-06-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PSY', 'Psychologie'), ('COMM', 'Communication Sociale'), ('SOCIO', 'Sociologie'), ('TS', 'Travail Social')], max_length=20, unique=True, verbose_name='Code')),
                ('slug', models.SlugField(help_text='Ex: psychologie, sociologie — utilisé dans les URLs et le JS', unique=True, verbose_name='Slug')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, verbose_name='Description courte (hero)')),
                ('couleur', models.CharField(choices=[('primary', 'Bleu (primary)'), ('secondary', 'Violet (secondary)'), ('success', 'Vert (success)'), ('accent', 'Jaune (accent)')], default='primary', max_length=20, verbose_name='Couleur CSS')),
                ('emoji', models.CharField(default='🎓', help_text='Affiché dans le bouton de navigation hero', max_length=10, verbose_name='Emoji')),
                ('slogan', models.CharField(blank=True, help_text="Ex: Comprendre l'esprit", max_length=100, verbose_name='Slogan court')),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='departements/hero/', verbose_name='Image hero')),
                ('image_hero_url', models.URLField(blank=True, help_text="URL Unsplash ou autre si pas d'upload", verbose_name='URL image hero (externe)')),
                ('nb_etudiants_affiche', models.CharField(default='—', max_length=20, verbose_name='Étudiants actifs (affiché)')),
                ('taux_reussite', models.CharField(default='—', max_length=10, verbose_name='Taux de réussite (affiché)')),
                ('taux_insertion', models.CharField(default='—', max_length=10, verbose_name='Taux insertion pro (affiché)')),
                ('date_limite_inscription', models.DateField(blank=True, null=True, verbose_name='Date limite inscription')),
                ('conditions_admission', models.TextField(blank=True, help_text='Une condition par ligne', verbose_name="Conditions d'admission")),
                ('specialites', models.TextField(blank=True, help_text='Ex: Psychologie Clinique, Psychologie Sociale', verbose_name='Spécialités (séparées par virgule)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('chef_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_dirige', to='comptes.professeur', verbose_name='Chef de département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
