# Generated by Django 4.2 on 2025-10-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du cours')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.IntegerField(default=3, verbose_name='Crédits')),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3')], max_length=1, verbose_name='Semestre')),
                ('annee_academique', models.CharField(max_length=9, verbose_name='Année académique')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('brouillon', 'Brouillon')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etudiants', models.ManyToManyField(blank=True, related_name='cours_inscrits', to='accounts.student', verbose_name='Étudiants')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to='accounts.professor', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
                'unique_together': {('code', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='soumissions/%Y/%m/', verbose_name='Fichier')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('note_max', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Note maximale')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('evaluee', 'Évaluée'), ('retard', 'En retard')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_limite', models.DateTimeField(blank=True, null=True, verbose_name='Date limite')),
                ('date_evaluation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='faculty.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='accounts.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ProjetRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('domaine', models.CharField(max_length=200, verbose_name='Domaine de recherche')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('revision', 'En révision'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('collaborateurs', models.ManyToManyField(blank=True, related_name='projets_collabores', to='accounts.professor', verbose_name='Collaborateurs')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_recherche', to='accounts.professor', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Projet de recherche',
                'verbose_name_plural': 'Projets de recherche',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='accounts.professor', verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='accounts.professor', verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_evenement', models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen'), ('devoir', 'Devoir'), ('reunion', 'Réunion'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='faculty.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
    ]
