# Generated by Django 4.2 on 2026-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Intitulé de l'examen")),
                ('date', models.DateField(verbose_name="Date de l'examen")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('active', 'En cours'), ('upcoming', 'À venir')], default='upcoming', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('resume', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('doyen', 'Doyen'), ('vice_doyen_acad', 'Vice-Doyen Académique'), ('vice_doyen_admin', 'Vice-Doyen Administratif'), ('secretaire', 'Secrétaire Général'), ('agent_admin', 'Agent Administratif'), ('rap', 'Responsable Année Préparatoire'), ('chef_dept_socio', 'Chef de Département de Sociologie'), ('chef_dept_psy', 'Chef de Département de Psychologie'), ('chef_dept_com', 'Chef de Département de Communication Sociale'), ('chef_dept_ss', 'Chef de Département de Service Social')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel administratif',
                'ordering': ['poste'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='FASCH', max_length=100)),
                ('nom_complet', models.CharField(default='Faculté des Sciences Humaines', max_length=200)),
                ('slogan', models.TextField(blank=True, default='Depuis 1975, FASCH forme les leaders de demain...')),
                ('annee_fondation', models.PositiveIntegerField(default=1975)),
                ('adresse_ligne1', models.CharField(blank=True, max_length=200)),
                ('adresse_ligne2', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lien_twitter', models.URLField(blank=True)),
                ('lien_facebook', models.URLField(blank=True)),
                ('lien_linkedin', models.URLField(blank=True)),
                ('annee_copyright', models.PositiveIntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
