# Generated by Django 4.2 on 2026-06-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_remove_sectioncours_unicite_section_par_professeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('resume', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription newsletter',
                'ordering': ['-inscrit_le'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('doyen', 'Doyen'), ('vice_doyen_acad', 'Vice-Doyen Académique'), ('vice_doyen_admin', 'Vice-Doyen Administratif'), ('secretaire', 'Secrétaire Général'), ('agent_admin', 'Agent Administratif'), ('rap', 'Responsable Année Préparatoire'), ('chef_dept_socio', 'Chef de Département de Sociologie'), ('chef_dept_psy', 'Chef de Département de Psychologie'), ('chef_dept_com', 'Chef de Département de Communication Sociale'), ('chef_dept_ss', 'Chef de Département de Service Social')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel administratif',
                'ordering': ['poste'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='FASCH', max_length=100)),
                ('nom_complet', models.CharField(default='Faculté des Sciences Humaines', max_length=200)),
                ('slogan', models.TextField(blank=True, default='Depuis 1975, FASCH forme les leaders de demain...')),
                ('annee_fondation', models.PositiveIntegerField(default=1975)),
                ('adresse_ligne1', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo petit (favicon/topbar)')),
                ('nom_directeur_etudes', models.CharField(blank=True, max_length=200, verbose_name='Nom du Directeur des Études')),
                ('titre_directeur_etudes', models.CharField(blank=True, default='Le Directeur des Études', max_length=200, verbose_name='Titre du Directeur des Études')),
                ('signature_directeur', models.ImageField(blank=True, null=True, upload_to='site/signatures/', verbose_name='Signature du Directeur (image)')),
                ('cachet_officiel', models.ImageField(blank=True, null=True, upload_to='site/cachets/', verbose_name='Cachet officiel')),
                ('lien_twitter', models.URLField(blank=True)),
                ('lien_facebook', models.URLField(blank=True)),
                ('lien_linkedin', models.URLField(blank=True)),
                ('annee_copyright', models.PositiveIntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('mi_parcours', 'Examen de mi-parcours'), ('final', 'Examen final'), ('rattrapage', 'Rattrapage')], default='final', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('salle', models.CharField(blank=True, max_length=100, verbose_name='Salle')),
                ('duree_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='Remarques')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('section_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='cours.sectioncours', verbose_name='Section de cours')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['date', 'heure'],
            },
        ),
    ]
