# Generated by Django 4.2 on 2026-06-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
        ('portail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Obligatoire uniquement pour le poste Chef de Département', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chefs_personnel', to='departements.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('doyen', 'Doyen'), ('vice_doyen_acad', 'Vice-Doyen Académique'), ('vice_doyen_admin', 'Vice-Doyen Administratif'), ('secretaire', 'Secrétaire Général'), ('agent_admin', 'Agent Administratif'), ('rap', 'Responsable Année Préparatoire'), ('chef_dept', 'Chef de Département')], max_length=50),
        ),
    ]
