# Generated by Django 4.2.16 on 2026-06-26 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['titre'], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('philosophie', 'Philosophie'), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('histoire_geo', 'Histoire & Géographie'), ('archeologie', 'Archéologie'), ('anthropologie', 'Anthropologie'), ('sociologie', 'Sociologie'), ('psychologie', 'Psychologie'), ('psycho_sociale', 'Psychologie sociale'), ('psycho_clinique', 'Psychologie clinique'), ('sciences_educ', "Sciences de l'éducation"), ('travail_social', 'Travail social'), ('demographe', 'Démographie'), ('droit', 'Droit'), ('droit_public', 'Droit public'), ('droit_prive', 'Droit privé'), ('droit_international', 'Droit international'), ('science_politique', 'Science politique'), ('relations_inter', 'Relations internationales'), ('economie', 'Économie'), ('economie_dev', 'Économie du développement'), ('gestion', 'Gestion & Administration'), ('comptabilite', 'Comptabilité & Finance'), ('litterature', 'Littérature'), ('litterature_fr', 'Littérature française'), ('litterature_comp', 'Littérature comparée'), ('linguistique', 'Linguistique'), ('langues', 'Langues étrangères'), ('traduction', 'Traduction & Interprétariat'), ('communication', 'Communication'), ('journalisme', 'Journalisme'), ('medias_numeriques', 'Médias & Communication numérique'), ('relations_pub', 'Relations publiques'), ('arts', 'Arts & Culture'), ('arts_plastiques', 'Arts plastiques'), ('musique', 'Musique'), ('cinema', 'Cinéma & Audiovisuel'), ('patrimoine', 'Patrimoine culturel'), ('statistiques', 'Statistiques & Méthodes quantitatives'), ('informatique', 'Informatique & Humanités numériques'), ('recherche', 'Méthodologie de la recherche'), ('interdisciplinaire', 'Interdisciplinaire'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='livres/couvertures/', verbose_name='Couverture'),
        ),
        migrations.AddField(
            model_name='livre',
            name='editeur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Éditeur'),
        ),
        migrations.AddField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='livre',
            name='nombre_exemplaires',
            field=models.PositiveIntegerField(default=1, verbose_name="Nombre d'exemplaires"),
        ),
        migrations.AlterField(
            model_name='livre',
            name='annee',
            field=models.IntegerField(verbose_name='Année de publication'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=200, verbose_name='Auteur(s)'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=datetime.date.today, verbose_name="Date d'emprunt")),
                ('date_retour_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('date_retour_effective', models.DateField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rendu', 'Rendu'), ('en_retard', 'En retard')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('note_admin', models.TextField(blank=True, verbose_name='Note interne')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='portail.livre', verbose_name='Livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('disponible', 'Disponible — à récupérer'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_disponibilite', models.DateField(blank=True, null=True, verbose_name="Disponible jusqu'au")),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='portail.livre', verbose_name='Livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_reservation'],
                'unique_together': {('utilisateur', 'livre')},
            },
        ),
    ]
