# Generated by Django 4.2 on 2026-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='adresse_ligne2',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='annee_copyright',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
