# Generated by Django 4.2 on 2026-06-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0002_remove_sitesettings_adresse_ligne2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cachet_officiel',
            field=models.ImageField(blank=True, null=True, upload_to='site/cachets/', verbose_name='Cachet officiel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_small',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo petit (favicon/topbar)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nom_directeur_etudes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du Directeur des Études'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signature_directeur',
            field=models.ImageField(blank=True, null=True, upload_to='site/signatures/', verbose_name='Signature du Directeur (image)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='titre_directeur_etudes',
            field=models.CharField(blank=True, default='Le Directeur des Études', max_length=200, verbose_name='Titre du Directeur des Études'),
        ),
    ]
