# Generated by Django 4.2 on 2026-06-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0004_messagecontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageContact',
        ),
    ]
