# Generated by Django 4.2 on 2026-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0005_delete_messagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription newsletter',
                'ordering': ['-inscrit_le'],
            },
        ),
    ]
