# Generated by Django 4.2 on 2026-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0006_newsletterinscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='status',
        ),
        migrations.AddField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('termine', 'Terminé'), ('en_cours', 'En cours'), ('a_venir', 'À venir')], default='a_venir', max_length=20, verbose_name='Statut'),
        ),
    ]
