# Generated by Django 4.2 on 2026-06-16 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('organisateur', models.CharField(blank=True, default='FASCH', max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Le titre de l'article", max_length=200)),
                ('contenu', models.TextField(help_text="Le contenu de l'article")),
                ('auteur', models.CharField(default='FASCH', max_length=100)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('est_active', models.BooleanField(default=True, help_text="Indique si l'article est actif ou non")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='Ex : 847 ou 2 341', max_length=20, verbose_name='Valeur')),
                ('libelle', models.CharField(help_text='Ex : Publications Totales', max_length=100, verbose_name='Libellé')),
                ('couleur', models.CharField(choices=[('primary', 'Bleu (primary)'), ('secondary', 'Rouge (secondary)'), ('success', 'Vert (success)'), ('accent', 'Violet (accent)')], default='primary', max_length=20, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, help_text='Ex : bi-book, bi-journal-text', max_length=50, verbose_name='Icône Bootstrap')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Métrique de recherche',
                'verbose_name_plural': 'Métriques de recherche',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('categorie', models.CharField(choices=[('gouvernement', 'Partenariats Gouvernementaux'), ('ong', 'Collaborations ONG'), ('international', 'Partenariats Internationaux')], max_length=20, verbose_name='Catégorie')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenariat',
                'verbose_name_plural': 'Partenariats',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('type_publication', models.CharField(choices=[('article', 'Article de recherche'), ('these', 'Thèse'), ('conference', 'Communication de conférence'), ('rapport', 'Rapport'), ('etudiant', 'Projet étudiant')], default='article', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('publie', 'Publié'), ('nouveau', 'Nouveau'), ('finaliste', 'Finaliste'), ('archive', 'Archivé')], default='publie', max_length=20, verbose_name='Statut')),
                ('langue', models.CharField(choices=[('francais', 'Français'), ('creole', 'Kreyòl Ayisyen'), ('anglais', 'Anglais')], default='francais', max_length=20, verbose_name='Langue')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu complet')),
                ('auteurs_texte', models.CharField(help_text='Noms séparés par des virgules', max_length=500, verbose_name='Auteurs (texte)')),
                ('revue', models.CharField(blank=True, max_length=300, verbose_name='Revue / Source')),
                ('annee_publication', models.IntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('periode_projet', models.CharField(blank=True, help_text='Ex : 2023-2025 ou Septembre 2025', max_length=50, verbose_name='Période du projet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Image de couverture')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='publications/pdf/', verbose_name='Fichier PDF')),
                ('est_vedette', models.BooleanField(default=False, help_text='Afficher dans la section « Recherches Vedettes »', verbose_name='Recherche vedette')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('nombre_citations', models.PositiveIntegerField(default=0, verbose_name='Citations')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-annee_publication', '-cree_le'],
            },
        ),
    ]
