# Generated by Django 4.2 on 2026-06-20 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('organisateur', models.CharField(blank=True, default='FASCH', max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('couleur', models.CharField(default='#e74c3c', max_length=7, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='Ex : 847 ou 2 341', max_length=20, verbose_name='Valeur')),
                ('libelle', models.CharField(help_text='Ex : Publications Totales', max_length=100, verbose_name='Libellé')),
                ('couleur', models.CharField(choices=[('primary', 'Bleu (primary)'), ('secondary', 'Rouge (secondary)'), ('success', 'Vert (success)'), ('accent', 'Violet (accent)')], default='primary', max_length=20, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, help_text='Ex : bi-book, bi-journal-text', max_length=50, verbose_name='Icône Bootstrap')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Métrique de recherche',
                'verbose_name_plural': 'Métriques de recherche',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('categorie', models.CharField(choices=[('gouvernement', 'Partenariats Gouvernementaux'), ('ong', 'Collaborations ONG'), ('international', 'Partenariats Internationaux')], max_length=20, verbose_name='Catégorie')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenariat',
                'verbose_name_plural': 'Partenariats',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('type_publication', models.CharField(choices=[('article', 'Article de recherche'), ('these', 'Thèse'), ('conference', 'Communication de conférence'), ('rapport', 'Rapport'), ('etudiant', 'Projet étudiant')], default='article', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('publie', 'Publié'), ('nouveau', 'Nouveau'), ('finaliste', 'Finaliste'), ('archive', 'Archivé')], default='publie', max_length=20, verbose_name='Statut')),
                ('langue', models.CharField(choices=[('francais', 'Français'), ('creole', 'Kreyòl Ayisyen'), ('anglais', 'Anglais')], default='francais', max_length=20, verbose_name='Langue')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu complet')),
                ('auteurs_texte', models.CharField(help_text='Noms séparés par des virgules', max_length=500, verbose_name='Auteurs (texte)')),
                ('revue', models.CharField(blank=True, max_length=300, verbose_name='Revue / Source')),
                ('annee_publication', models.IntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('periode_projet', models.CharField(blank=True, help_text='Ex : 2023-2025 ou Septembre 2025', max_length=50, verbose_name='Période du projet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Image de couverture')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='publications/pdf/', verbose_name='Fichier PDF')),
                ('est_vedette', models.BooleanField(default=False, help_text='Afficher dans la section « Recherches Vedettes »', verbose_name='Recherche vedette')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('nombre_citations', models.PositiveIntegerField(default=0, verbose_name='Citations')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('auteur_etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.etudiant', verbose_name='Auteur étudiant')),
                ('auteur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.professeur', verbose_name='Auteur principal (professeur)')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='departements.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-annee_publication', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('extrait', models.TextField(blank=True, max_length=400, verbose_name='Extrait')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='Image principale')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En revision'), ('publie', 'Publie')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('est_a_la_une', models.BooleanField(default=False, verbose_name='Article a la une')),
                ('est_breaking', models.BooleanField(default=False, verbose_name='Breaking news')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_set', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.categorie', verbose_name='Categorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publie_le', '-cree_le'],
            },
        ),
    ]
