# Generated by Django 4.2 on 2026-06-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('comptes', '0001_initial'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='auteur_etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.etudiant', verbose_name='Auteur étudiant'),
        ),
        migrations.AddField(
            model_name='publication',
            name='auteur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.professeur', verbose_name='Auteur principal (professeur)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='departements.departement', verbose_name='Département'),
        ),
    ]
