# Generated by Django 4.2.16 on 2026-06-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='auteur_etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.etudiant', verbose_name='Auteur étudiant'),
        ),
        migrations.AddField(
            model_name='publication',
            name='auteur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='comptes.professeur', verbose_name='Auteur principal (professeur)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='departements.departement', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_set', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.categorie', verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.tag', verbose_name='Tags'),
        ),
    ]
