# Generated by Django 4.2.16 on 2026-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(choices=[('general', 'Demande generale'), ('redaction', 'Contacter la redaction'), ('correction', 'Signaler une erreur'), ('partenariat', 'Proposition de partenariat'), ('publicite', 'Publicite'), ('technique', 'Probleme technique'), ('autre', 'Autre')], default='general', max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(max_length=3000, verbose_name='Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
