# Generated by Django 4.2 on 2025-10-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du cours')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.IntegerField(verbose_name='Crédits')),
                ('year_level', models.IntegerField(choices=[(1, 'Année Préparatoire'), (2, 'Deuxième Année'), (3, 'Troisième Année'), (4, 'Quatrième Année')], verbose_name="Année d'études")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course', verbose_name='Cours')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course', verbose_name='Cours prérequis')),
            ],
            options={
                'verbose_name': 'Prérequis',
                'verbose_name_plural': 'Prérequis',
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10, verbose_name='Numéro de section')),
                ('day_of_week', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('session', models.CharField(choices=[('SESSION_1', 'Session 1'), ('SESSION_2', 'Session 2')], max_length=20, verbose_name='Session')),
                ('semester', models.CharField(choices=[('FALL', 'Automne'), ('SPRING', 'Printemps'), ('SUMMER', 'Été')], max_length=20, verbose_name='Semestre')),
                ('year', models.IntegerField(verbose_name='Année académique')),
                ('max_students', models.IntegerField(default=30, verbose_name="Nombre maximum d'étudiants")),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert aux inscriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='Cours')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='accounts.professor', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Section de cours',
                'verbose_name_plural': 'Sections de cours',
                'ordering': ['course__code', 'section_number'],
                'unique_together': {('course', 'section_number', 'session', 'semester', 'year')},
            },
        ),
    ]
