# Generated by Django 4.2 on 2025-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'section_number', 'professor', 'session', 'semester', 'year'), name='unique_course_section_per_professor'),
        ),
    ]
