# Generated by Django 4.2.16 on 2026-06-25 21:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('SUPERUTILISATEUR', 'Super Utilisateur'), ('ADMIN', 'Administrateur'), ('PROFESSEUR', 'Professeur'), ('ETUDIANT', 'Étudiant')], max_length=20, verbose_name='Rôle')),
                ('role_editorial', models.CharField(choices=[('LECTEUR', 'Lecteur'), ('AUTEUR', 'Auteur'), ('EDITEUR', 'Éditeur')], default='LECTEUR', max_length=20, verbose_name='Rôle éditorial')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre')),
                ('numero_telephone', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format : '+999999999'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('doit_changer_mot_de_passe', models.BooleanField(default=True, verbose_name='Doit changer le mot de passe')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_administrateur', models.CharField(max_length=20, unique=True, verbose_name='ID Administrateur')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True, verbose_name='Numéro étudiant')),
                ('niveau', models.CharField(choices=[('PREPARATOIRE', 'Préparatoire'), ('NIVEAU1', 'Niveau I'), ('NIVEAU2', 'Niveau II'), ('NIVEAU3', 'Niveau III')], max_length=20, verbose_name='Niveau actuel')),
                ('date_inscription', models.DateField(verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['numero_etudiant'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_professeur', models.CharField(max_length=20, unique=True, verbose_name='ID Professeur')),
                ('specialite', models.CharField(blank=True, max_length=200, verbose_name='Spécialisation')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['identifiant_professeur'],
            },
        ),
    ]
