# Generated by Django 4.2 on 2026-06-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role_editorial',
            field=models.CharField(choices=[('LECTEUR', 'Lecteur'), ('AUTEUR', 'Auteur'), ('EDITEUR', 'Éditeur')], default='LECTEUR', max_length=20, verbose_name='Rôle éditorial'),
        ),
    ]
