# Generated by Django 4.2.16 on 2026-06-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du cours')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.IntegerField(verbose_name='Crédits')),
                ('niveau', models.CharField(choices=[('PREPARATOIRE', 'Préparatoire'), ('NIVEAU1', 'Niveau I'), ('NIVEAU2', 'Niveau II'), ('NIVEAU3', 'Niveau III')], max_length=15)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='departements.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SectionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_section', models.CharField(max_length=10, verbose_name='Numéro de section')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('session', models.CharField(choices=[('SESSION_1', 'Session 1'), ('SESSION_2', 'Session 2')], max_length=20, verbose_name='Session')),
                ('semestre', models.CharField(choices=[('AUTOMNE', 'Automne'), ('PRINTEMPS', 'Printemps'), ('ETE', 'Été')], max_length=20, verbose_name='Semestre')),
                ('annee', models.IntegerField(verbose_name='Année académique')),
                ('capacite_max', models.IntegerField(default=30, verbose_name="Nombre maximum d'étudiants")),
                ('est_ouverte', models.BooleanField(default=True, verbose_name='Ouvert aux inscriptions')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cours.cours', verbose_name='Cours')),
                ('professeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_cours', to='comptes.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Section de cours',
                'verbose_name_plural': 'Sections de cours',
                'ordering': ['cours__code', 'numero_section'],
            },
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='cours.cours', verbose_name='Cours')),
                ('cours_prerequis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requis_pour', to='cours.cours', verbose_name='Cours prérequis')),
            ],
            options={
                'verbose_name': 'Prérequis',
                'verbose_name_plural': 'Prérequis',
            },
        ),
        migrations.AddConstraint(
            model_name='sectioncours',
            constraint=models.UniqueConstraint(fields=('cours', 'numero_section', 'session', 'semestre', 'annee'), name='unicite_section_par_periode'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequis',
            unique_together={('cours', 'cours_prerequis')},
        ),
    ]
