# Generated by Django 4.2 on 2026-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectioncours',
            name='unicite_section_par_professeur',
        ),
        migrations.AddConstraint(
            model_name='sectioncours',
            constraint=models.UniqueConstraint(fields=('cours', 'numero_section', 'session', 'semestre', 'annee'), name='unicite_section_par_periode'),
        ),
    ]
