# Generated by Django 4.2.16 on 2026-06-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ABANDONNE', 'Abandonné'), ('COMPLETE', 'Complété'), ('ECHOUE', 'Échoué')], default='INSCRIT', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_abandon', models.DateTimeField(blank=True, null=True, verbose_name="Date d'abandon")),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='comptes.etudiant', verbose_name='Étudiant')),
                ('section_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.sectioncours', verbose_name='Section de cours')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'section_cours')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(max_length=20, verbose_name='Statut précédent')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('modifie_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('raison', models.TextField(blank=True, verbose_name='Raison')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inscriptions.inscription', verbose_name='Inscription')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Historique d'inscription",
                'verbose_name_plural': "Historiques d'inscription",
                'ordering': ['-modifie_le'],
            },
        ),
    ]
