# Generated by Django 4.2 on 2026-06-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='departements.departement', verbose_name='Programme souhaité'),
        ),
        migrations.AddField(
            model_name='ambassadeur',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassadeurs', to='departements.departement', verbose_name="Programme d'études"),
        ),
    ]
