# Generated by Django 4.2.16 on 2026-06-25 21:28

import applications.devoirs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('consignes', models.TextField(blank=True, verbose_name='Consignes détaillées')),
                ('type_devoir', models.CharField(choices=[('FICHIER', 'Remise de fichier'), ('TEXTE', 'Réponse texte'), ('QCM', 'Questionnaire')], default='FICHIER', max_length=20, verbose_name='Type de devoir')),
                ('date_publication', models.DateTimeField(blank=True, help_text='Laisser vide pour publier immédiatement à la création.', null=True, verbose_name='Date de publication')),
                ('date_limite', models.DateTimeField(verbose_name='Date limite de remise')),
                ('points_max', models.IntegerField(default=100, verbose_name='Points maximum')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('section_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='cours.sectioncours')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_limite'],
            },
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, verbose_name='Réponse texte')),
                ('statut', models.CharField(choices=[('RENDU', 'Rendu'), ('EN_RETARD', 'Rendu en retard'), ('NOTE', 'Noté')], default='RENDU', max_length=20, verbose_name='Statut')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Note')),
                ('commentaire_prof', models.TextField(blank=True, verbose_name='Commentaire du professeur')),
                ('remis_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='devoirs.devoir')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='comptes.etudiant')),
            ],
            options={
                'verbose_name': 'Remise',
                'verbose_name_plural': 'Remises',
                'ordering': ['-remis_le'],
                'unique_together': {('devoir', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='FichierRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=applications.devoirs.models.chemin_fichier_remise, verbose_name='Fichier')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('remise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='devoirs.remise')),
            ],
            options={
                'verbose_name': 'Fichier de remise',
                'ordering': ['ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='FichierDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=applications.devoirs.models.chemin_fichier_devoir, verbose_name='Fichier')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom affiché')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='devoirs.devoir')),
            ],
            options={
                'verbose_name': 'Fichier joint (devoir)',
                'ordering': ['cree_le'],
            },
        ),
    ]
