# Generated by Django 4.2 on 2026-06-16 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_mi_parcours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Examen de mi-parcours')),
                ('examen_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Examen final')),
                ('travaux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Travaux/Devoirs')),
                ('participation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participation')),
                ('projet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Projet')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Note finale')),
                ('mention', models.CharField(blank=True, max_length=2, verbose_name='Mention')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='inscriptions.inscription', verbose_name='Inscription')),
                ('note_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_notes', to='comptes.professeur', verbose_name='Noté par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composante', models.CharField(max_length=50, verbose_name='Composante')),
                ('ancienne_valeur', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Nouvelle valeur')),
                ('modifie_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('raison', models.TextField(blank=True, verbose_name='Raison')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.professeur', verbose_name='Modifié par')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='notes.note', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Historique de note',
                'verbose_name_plural': 'Historiques de notes',
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre')),
                ('annee', models.IntegerField(verbose_name='Année académique')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Moyenne générale (GPA)')),
                ('credits_tentes', models.IntegerField(default=0, verbose_name='Crédits tentés')),
                ('credits_obtenus', models.IntegerField(default=0, verbose_name='Crédits obtenus')),
                ('genere_le', models.DateTimeField(auto_now=True, verbose_name='Date de génération')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='comptes.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Relevé de notes',
                'verbose_name_plural': 'Relevés de notes',
                'ordering': ['-annee', '-semestre'],
                'unique_together': {('etudiant', 'semestre', 'annee')},
            },
        ),
    ]
