# Generated by Django 4.2 on 2026-06-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_bulletin_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mention',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mention'),
        ),
    ]
