# Generated by Django 4.2 on 2026-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mention',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Très bien', 'Très bien'), ('Bien', 'Bien'), ('Passable', 'Passable'), ('Échec', 'Échec')], max_length=10, verbose_name='Mention'),
        ),
    ]
