# Generated by Django 4.2.16 on 2026-06-23 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0001_initial'),
        ('notes', '0004_alter_note_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDeclaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_declaree', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire_etudiant', models.TextField(blank=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('declare_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_declaree', to='inscriptions.inscription')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note déclarée',
                'verbose_name_plural': 'Notes déclarées',
            },
        ),
    ]
